#!/bin/bash

cat pkgs.txt | grep Initialized > /dev/null
if [[ $? -ne 0 ]]; then
    sudo sh -c "echo 'deb https://http.kali.org/kali kali-rolling main non-free contrib' > /etc/apt/sources.list.d/kali.list"
    sudo apt install gnupg
    wget 'https://archive.kali.org/archive-key.asc'
    sudo apt-key add archive-key.asc
    sudo sh -c "echo 'Package: *'>/etc/apt/preferences.d/kali.pref; echo 'Pin: release a=kali-rolling'>>/etc/apt/preferences.d/kali.pref; echo 'Pin-Priority: 50'>>/etc/apt/preferences.d/kali.pref"
    sudo apt update
    echo "Initialized" >> pkgs.txt
else
    echo "Already initialized."
fi

inst() {
    _pkg=$1
    apt-cache show "${_pkg}" &>  /dev/null
    if [ $? -ne 0 ]; then
        echo    
        echo $_pkg
        read -n 1 -r -s -p $'Press enter to continue...\n'
        echo $_pkg >> pkgs.txt
        sudo apt install -y -t kali-rolling $_pkg
        _res=$?
        sudo apt autoremove
        sudo apt --fix-broken install
        if [ $_res -ne 0 ]; then
            echo "${_res} Failed. Should abort."
            return 1 2>/dev/null
            exit 1
        fi        
        echo $_pkg >> pkgs.txt
    else
        echo    
        echo "${_pkg} already installed"
    fi
}

echo "" >> pkgs.txt
inst 0trace
inst aesfix
inst aeskeyfind
inst afflib
inst aflplusplus
inst aircrack-ng
inst airgeddon
inst b374k
inst backdoor-factory
inst bed
inst beef-xss
inst berate-ap
inst bettercap
inst bettercap-ui
inst bind9
inst bing-ip2hosts
inst binwalk
inst bloodhound
inst bloodhound.py
inst bluelog
inst blueranger
inst bluesnarfer
inst bluez
inst braa
inst bruteforce-luks
inst bruteforce-salted-openssl
inst bruteforce-wallet
inst bruteshark
inst brutespray
inst btscanner
inst bulk-extractor
inst bully
inst burpsuite
inst bytecode-viewer
inst cabextract
inst cadaver
inst caldera
inst calico
inst capstone
inst ccrypt
inst certgraph
inst certipy-ad
inst cewl
inst changeme
inst chaosreader
inst cherrytree
inst chirp
inst chisel
inst chkrootkit
inst chntpw
inst chromium
inst cifs-utils
inst cilium-cli
inst cisco-auditing-tool
inst cisco-global-exploiter
inst cisco-ocs
inst cisco-torch
inst cisco7crack
inst clamav
inst cloud-enum
inst cloudbrute
inst cmospwd
inst cmseek
inst cntlm
inst code-oss
inst colly
inst command-not-found
inst commix
inst copy-router-config
inst cosign
inst covenant-kbx
inst cowpatty
inst crack
inst crackle
inst crackmapexec
inst creddump7
inst cri-tools
inst crowbar
inst crunch
inst cryptcat
inst cryptsetup
inst cryptsetup-nuke-password
inst cupid-wpa
inst curl
inst curlftpfs
inst cutecom
inst cutycapt
inst cymothoa
inst darkstat
inst davtest
inst dbd
inst dbeaver
inst dc3dd
inst dcfldd
inst ddrescue
inst de4dot
inst defectdojo
inst dex2jar
inst dfdatetime
inst dfvfs
inst dfwinreg
inst dhcpig
inst dirb
inst dirbuster
inst dirsearch
inst dislocker
inst distorm3
inst dmitry
inst dns2tcp
inst dnscat2
inst dnschef
inst dnsenum
inst dnsgen
inst dnsmap
inst dnsrecon
inst dnstracer
inst dnstwist
inst dnswalk
inst dnsx
inst doona
inst dos2unix
inst dotdotpwn
inst dradis
inst driftnet
inst dscan
inst dsniff
inst dufflebag
inst dumpsterdiver
inst dumpzilla
inst dvwa
inst dwarf2json
inst eaphammer
inst eapmd5pass
inst edb-debugger
inst eksctl
inst email2phonenumber
inst emailharvester
inst enum4linux
inst enum4linux-ng
inst enumiax
inst ethtool
inst ettercap
inst evil-ssdp
inst evil-winrm
inst evilginx2
inst exe2hexbat
inst exiflooter
inst exifprobe
inst exiv2
inst expect
inst exploitdb
inst exploitdb-bin-sploits
inst exploitdb-papers
inst ext3grep
inst ext4magic
inst extundelete
inst eyewitness
inst faraday-agent-dispatcher
inst faraday-cli
inst fatcat
inst fcrackzip
inst fern-wifi-cracker
inst feroxbuster
inst ferret-sidejack
inst ffuf
inst fierce
inst fiked
inst finalrecon
inst firefox-developer-edition-kbx
inst firewalk
inst firmware-mod-kit
inst flashrom
inst foremost
inst forensic-artifacts
inst forensics-colorize
inst fping
inst fragrouter
inst framework2
inst freeradius
inst freeradius-wpe
inst freerdp2
inst ftester
inst fuse3
inst fwbuilder
inst galleta
inst gdb-peda
inst gdisk
inst getallurls
inst ghidra
inst git
inst gitleaks
inst glibc
inst gnuradio
inst gobuster
inst godoh
inst golang-github-binject-go-donut
inst goldeneye
inst goofile
inst google-nexus-tools
inst gophish
inst gospider
inst gpart
inst gparted
inst gpp-decrypt
inst gqrx-sdr
inst gr-air-modes
inst gr-iqbal
inst gr-osmosdr
inst grokevt
inst gss-ntlmssp
inst gtkhash
inst guymager
inst gvm
inst h8mail
inst hackrf
inst hak5-wifi-coconut
inst hakrawler
inst hamster-sidejack
inst hash-identifier
inst hashcat
inst hashcat-utils
inst hashdeep
inst hashid
inst hashrat
inst havoc
inst hb-honeypot
inst hcxtools
inst heartleech
inst hexinject
inst hivex
inst hostapd-mana
inst hostapd-wpe
inst hosthunter
inst hostsman
inst hotpatch
inst hping3
inst htshells
inst httprint
inst httprobe
inst httpx-toolkit
inst httrack
inst hubble
inst humble
inst hurl
inst hydra
inst hyperion
inst i2c-tools
inst iaxflood
inst ibombshell
inst ident-user-enum
inst ifenslave
inst ike-scan
inst imhex
inst impacket
inst impacket-scripts
inst inetsim
inst inspectrum
inst inspy
inst instaloader
inst intrace
inst inviteflood
inst iodine
inst ipv6toolkit
inst irpas
inst ismtp
inst isr-evilgrade
inst ivre
inst iw
inst jadx
inst javasnoop
inst jboss-autopwn
inst jd-gui
inst john
inst johnny
inst joomscan
inst joplin
inst jsp-file-browser
inst jsql
inst juice-shop
inst kali-autopilot
inst kali-community-wallpapers
inst kali-defaults
inst kali-meta
inst kali-tweaks
inst kali-wallpapers
inst kalibrate-rtl
inst kerberoast
inst kismet
inst knocker
inst koadic
inst kubernetes-helm
inst kustomize
inst lapsdumper
inst laudanum
inst lbd
inst legion
inst libewf
inst libfindrtp
inst libfreefare
inst libimage-exiftool-perl
inst libnfc
inst libpst
inst libsmali-java
inst linux-exploit-suggester
inst llvm-defaults
inst lvm2
inst lynis
inst mac-robber
inst macchanger
inst magicrescue
inst maltego
inst maltego-teeth
inst maryam
inst maskprocessor
inst masscan
inst massdns
inst mc
inst mdbtools
inst mdk3
inst mdk4
inst medusa
inst memdump
inst mercurial
inst merlin
inst merlin-agent
inst metacam
inst metagoofil
inst metasploit-framework
inst mfcuk
inst mfoc
inst mfterm
inst mimikatz
inst minicom
inst miredo
inst missidentify
inst mitmproxy
inst mongo-tools
inst msfpc
inst multiforcer
inst multimac
inst multimon-ng
inst myrescue
inst mysql-defaults
inst naabu
inst name-that-hash
inst nasm
inst nasty
inst nbtscan
inst nbtscan-unixwiz
inst ncat-w32
inst ncrack
inst ncurses-hexedit
inst net-snmp
inst net-tools
inst netbase
inst netcat
inst netdiscover
inst netmask
inst netsed
inst netsniff-ng
inst netw-ib-ox-ag
inst nextnet
inst nfs-utils
inst ngrep
inst nikto
inst nipper-ng
inst nishang
inst nmap
inst nmapsi4
inst nuclei
inst o-saft
inst oclgausscrack
inst odat
inst offsec-courses
inst ohrwurm
inst ollydbg
inst onesixtyone
inst openocd
inst openssh
inst openvpn
inst ophcrack
inst oscanner
inst osrframework
inst outguess
inst owasp-mantra-ff
inst owl
inst p0f
inst p7zip
inst pack
inst pack2
inst pacu
inst padbuster
inst paros
inst parsero
inst parted
inst pasco
inst passdetective
inst passing-the-hash
inst patator
inst payloadsallthethings
inst pdf-parser
inst pdfcrack
inst pdfid
inst peass-ng
inst peirates
inst perl-cisco-copyconfig
inst pev
inst phishery
inst photon
inst php-defaults
inst phpggc
inst phpsploit
inst pipal
inst pixiewps
inst plaso
inst plocate
inst pnscan
inst pocsuite3
inst polenum
inst pompem
inst portspoof
inst poshc2
inst powercat
inst powershell
inst powershell-empire
inst powersploit
inst princeprocessor
inst protos-sip
inst proxify
inst proxmark3
inst proxychains-ng
inst proxytunnel
inst pskracker
inst ptunnel
inst pwnat
inst pwncat
inst python-defaults
inst python-faraday
inst python-ldapdomaindump
inst python-pip
inst python-virtualenv
inst qemu
inst qsslcaudit
inst quark-engine
inst radare2
inst rainbowcrack
inst rake
inst rarcrack
inst raven
inst rcracki-mt
inst rdesktop
inst reaver
inst rebind
inst recon-ng
inst reconspider
inst recordmydesktop
inst recoverdm
inst recoverjpeg
inst redeye
inst redfang
inst redsnarf
inst redsocks
inst reglookup
inst regripper
inst rekono-kbx
inst rephrase
inst requests
inst responder
inst rev-proxy-grapher
inst rfcat
inst rfdump
inst ridenum
inst rifiuti
inst rifiuti2
inst rizin-cutter
inst rkhunter
inst rling
inst robotstxt
inst ropper
inst routerkeygenpc
inst routersploit
inst rsakeyfind
inst rsmangler
inst rtlsdr-scanner
inst rtpbreak
inst rtpflood
inst rtpinsertsound
inst rtpmixsound
inst ruby-pedump
inst rz-ghidra
inst s3scanner
inst safecopy
inst sakis3g
inst samba
inst samdump2
inst sbd
inst scalpel
inst scapy
inst screen
inst scrounge-ntfs
inst sctpscan
inst seclists
inst secure-socket-funneling
inst sendemail
inst sentrypeer
inst set
inst sfuzz
inst shed
inst shellfire
inst shellnoob
inst shellter
inst sherlock
inst sidguesser
inst siege
inst sigma-cli
inst silenttrinity
inst siparmyknife
inst sipcrack
inst sipp
inst sipsak
inst sipvicious
inst skipfish
inst sleuthkit
inst slimtoolkit
inst sliver
inst slowhttptest
inst smbmap
inst smtp-user-enum
inst sn0int
inst sniffjoke
inst snmpcheck
inst snmpenum
inst snowdrop
inst socat
inst sparrow-wifi
inst spectools
inst spiderfoot
inst spike
inst spire
inst spooftooph
inst spray
inst sprayingtoolkit
inst spraykatz
inst sqldict
inst sqlitebrowser
inst sqlmap
inst sqlninja
inst sqlsus
inst ssdeep
inst ssldump
inst sslh
inst sslscan
inst sslsniff
inst sslsplit
inst sslstrip
inst sslyze
inst statsprocessor
inst stegcracker
inst steghide
inst stegsnow
inst stunnel4
inst subfinder
inst subjack
inst sublist3r
inst subversion
inst sucrack
inst sudo
inst swaks
inst syft
inst t50
inst tcpdump
inst tcpflow
inst tcpick
inst tcpreplay
inst teamsploit
inst termineter
inst terraform
inst testdisk
inst testssl.sh
inst tetragon
inst tftp-hpa
inst tftpd32
inst thc-ipv6
inst thc-pptp-bruter
inst thc-ssl-dos
inst theharvester
inst tiger
inst tightvnc
inst tlssled
inst tmux
inst tnftp
inst tnscmd10g
inst traceroute
inst trivy
inst truecrack
inst trufflehog
inst tundeep
inst twofi
inst tzdata
inst ubertooth
inst udptunnel
inst uhd
inst uhd-images
inst unar
inst unblob
inst undbx
inst unhide
inst unhide.rb
inst unicorn-magic
inst unicornscan
inst uniscan
inst unix-privesc-check
inst unrar-nonfree
inst upx-ucl
inst urlcrazy
inst util-linux
inst vboot-utils
inst veil
inst villain
inst vim
inst vinetto
inst vlan
inst voiphopper
inst vpnc
inst wafw00f
inst wapiti
inst watobo
inst wce
inst webacoo
inst webscarab
inst webshells
inst websploit
inst weevely
inst wfuzz
inst wget
inst wgetpaste
inst what-is-python
inst whatmask
inst whatweb
inst whois
inst wifi-honey
inst wifiphisher
inst wifipumpkin3
inst wifite
inst wig
inst wig-ng
inst windows-binaries
inst windows-privesc-check
inst winexe
inst winregfs
inst wireshark
inst witnessme
inst wmi
inst wordlistraider
inst wordlists
inst wotmate
inst wpa-sycophant
inst wpscan
inst wsgidav
inst xmount
inst xplico
inst xspy
inst xsser
inst yara
inst yersinia
inst zaproxy
inst zenmap-kbx
inst zerofree
inst zim
inst zonedb
inst zsh
inst zsh-autosuggestions
inst zsh-syntax-highlighting
