#!/bin/bash

sudo sh -c "echo 'deb https://http.kali.org/kali kali-rolling main non-free contrib' > /etc/apt/sources.list.d/kali.list"
sudo apt install gnupg
wget 'https://archive.kali.org/archive-key.asc'
sudo apt-key add archive-key.asc
sudo sh -c "echo 'Package: *'>/etc/apt/preferences.d/kali.pref; echo 'Pin: release a=kali-rolling'>>/etc/apt/preferences.d/kali.pref; echo 'Pin-Priority: 50'>>/etc/apt/preferences.d/kali.pref"
sudo apt update

sudo apt install -y -t kali-rolling 0trace
sudo apt install -y -t kali-rolling aesfix
sudo apt install -y -t kali-rolling aeskeyfind
sudo apt install -y -t kali-rolling afflib
sudo apt install -y -t kali-rolling aflplusplus
sudo apt install -y -t kali-rolling aircrack-ng
sudo apt install -y -t kali-rolling airgeddon
sudo apt install -y -t kali-rolling b374k
sudo apt install -y -t kali-rolling backdoor-factory
sudo apt install -y -t kali-rolling bed
sudo apt install -y -t kali-rolling beef-xss
sudo apt install -y -t kali-rolling berate-ap
sudo apt install -y -t kali-rolling bettercap
sudo apt install -y -t kali-rolling bettercap-ui
sudo apt install -y -t kali-rolling bind9
sudo apt install -y -t kali-rolling bing-ip2hosts
sudo apt install -y -t kali-rolling binwalk
sudo apt install -y -t kali-rolling bloodhound
sudo apt install -y -t kali-rolling bloodhound.py
sudo apt install -y -t kali-rolling bluelog
sudo apt install -y -t kali-rolling blueranger
sudo apt install -y -t kali-rolling bluesnarfer
sudo apt install -y -t kali-rolling bluez
sudo apt install -y -t kali-rolling braa
sudo apt install -y -t kali-rolling bruteforce-luks
sudo apt install -y -t kali-rolling bruteforce-salted-openssl
sudo apt install -y -t kali-rolling bruteforce-wallet
sudo apt install -y -t kali-rolling bruteshark
sudo apt install -y -t kali-rolling brutespray
sudo apt install -y -t kali-rolling btscanner
sudo apt install -y -t kali-rolling bulk-extractor
sudo apt install -y -t kali-rolling bully
sudo apt install -y -t kali-rolling burpsuite
sudo apt install -y -t kali-rolling bytecode-viewer
sudo apt install -y -t kali-rolling cabextract
sudo apt install -y -t kali-rolling cadaver
sudo apt install -y -t kali-rolling caldera
sudo apt install -y -t kali-rolling calico
sudo apt install -y -t kali-rolling capstone
sudo apt install -y -t kali-rolling ccrypt
sudo apt install -y -t kali-rolling certgraph
sudo apt install -y -t kali-rolling certipy-ad
sudo apt install -y -t kali-rolling cewl
sudo apt install -y -t kali-rolling changeme
sudo apt install -y -t kali-rolling chaosreader
sudo apt install -y -t kali-rolling cherrytree
sudo apt install -y -t kali-rolling chirp
sudo apt install -y -t kali-rolling chisel
sudo apt install -y -t kali-rolling chkrootkit
sudo apt install -y -t kali-rolling chntpw
sudo apt install -y -t kali-rolling chromium
sudo apt install -y -t kali-rolling cifs-utils
sudo apt install -y -t kali-rolling cilium-cli
sudo apt install -y -t kali-rolling cisco-auditing-tool
sudo apt install -y -t kali-rolling cisco-global-exploiter
sudo apt install -y -t kali-rolling cisco-ocs
sudo apt install -y -t kali-rolling cisco-torch
sudo apt install -y -t kali-rolling cisco7crack
sudo apt install -y -t kali-rolling clamav
sudo apt install -y -t kali-rolling cloud-enum
sudo apt install -y -t kali-rolling cloudbrute
sudo apt install -y -t kali-rolling cmospwd
sudo apt install -y -t kali-rolling cmseek
sudo apt install -y -t kali-rolling cntlm
sudo apt install -y -t kali-rolling code-oss
sudo apt install -y -t kali-rolling colly
sudo apt install -y -t kali-rolling command-not-found
sudo apt install -y -t kali-rolling commix
sudo apt install -y -t kali-rolling copy-router-config
sudo apt install -y -t kali-rolling cosign
sudo apt install -y -t kali-rolling covenant-kbx
sudo apt install -y -t kali-rolling cowpatty
sudo apt install -y -t kali-rolling crack
sudo apt install -y -t kali-rolling crackle
sudo apt install -y -t kali-rolling crackmapexec
sudo apt install -y -t kali-rolling creddump7
sudo apt install -y -t kali-rolling cri-tools
sudo apt install -y -t kali-rolling crowbar
sudo apt install -y -t kali-rolling crunch
sudo apt install -y -t kali-rolling cryptcat
sudo apt install -y -t kali-rolling cryptsetup
sudo apt install -y -t kali-rolling cryptsetup-nuke-password
sudo apt install -y -t kali-rolling cupid-wpa
sudo apt install -y -t kali-rolling curl
sudo apt install -y -t kali-rolling curlftpfs
sudo apt install -y -t kali-rolling cutecom
sudo apt install -y -t kali-rolling cutycapt
sudo apt install -y -t kali-rolling cymothoa
sudo apt install -y -t kali-rolling darkstat
sudo apt install -y -t kali-rolling davtest
sudo apt install -y -t kali-rolling dbd
sudo apt install -y -t kali-rolling dbeaver
sudo apt install -y -t kali-rolling dc3dd
sudo apt install -y -t kali-rolling dcfldd
sudo apt install -y -t kali-rolling ddrescue
sudo apt install -y -t kali-rolling de4dot
sudo apt install -y -t kali-rolling defectdojo
sudo apt install -y -t kali-rolling dex2jar
sudo apt install -y -t kali-rolling dfdatetime
sudo apt install -y -t kali-rolling dfvfs
sudo apt install -y -t kali-rolling dfwinreg
sudo apt install -y -t kali-rolling dhcpig
sudo apt install -y -t kali-rolling dirb
sudo apt install -y -t kali-rolling dirbuster
sudo apt install -y -t kali-rolling dirsearch
sudo apt install -y -t kali-rolling dislocker
sudo apt install -y -t kali-rolling distorm3
sudo apt install -y -t kali-rolling dmitry
sudo apt install -y -t kali-rolling dns2tcp
sudo apt install -y -t kali-rolling dnscat2
sudo apt install -y -t kali-rolling dnschef
sudo apt install -y -t kali-rolling dnsenum
sudo apt install -y -t kali-rolling dnsgen
sudo apt install -y -t kali-rolling dnsmap
sudo apt install -y -t kali-rolling dnsrecon
sudo apt install -y -t kali-rolling dnstracer
sudo apt install -y -t kali-rolling dnstwist
sudo apt install -y -t kali-rolling dnswalk
sudo apt install -y -t kali-rolling dnsx
sudo apt install -y -t kali-rolling doona
sudo apt install -y -t kali-rolling dos2unix
sudo apt install -y -t kali-rolling dotdotpwn
sudo apt install -y -t kali-rolling dradis
sudo apt install -y -t kali-rolling driftnet
sudo apt install -y -t kali-rolling dscan
sudo apt install -y -t kali-rolling dsniff
sudo apt install -y -t kali-rolling dufflebag
sudo apt install -y -t kali-rolling dumpsterdiver
sudo apt install -y -t kali-rolling dumpzilla
sudo apt install -y -t kali-rolling dvwa
sudo apt install -y -t kali-rolling dwarf2json
sudo apt install -y -t kali-rolling eaphammer
sudo apt install -y -t kali-rolling eapmd5pass
sudo apt install -y -t kali-rolling edb-debugger
sudo apt install -y -t kali-rolling eksctl
sudo apt install -y -t kali-rolling email2phonenumber
sudo apt install -y -t kali-rolling emailharvester
sudo apt install -y -t kali-rolling enum4linux
sudo apt install -y -t kali-rolling enum4linux-ng
sudo apt install -y -t kali-rolling enumiax
sudo apt install -y -t kali-rolling ethtool
sudo apt install -y -t kali-rolling ettercap
sudo apt install -y -t kali-rolling evil-ssdp
sudo apt install -y -t kali-rolling evil-winrm
sudo apt install -y -t kali-rolling evilginx2
sudo apt install -y -t kali-rolling exe2hexbat
sudo apt install -y -t kali-rolling exiflooter
sudo apt install -y -t kali-rolling exifprobe
sudo apt install -y -t kali-rolling exiv2
sudo apt install -y -t kali-rolling expect
sudo apt install -y -t kali-rolling exploitdb
sudo apt install -y -t kali-rolling exploitdb-bin-sploits
sudo apt install -y -t kali-rolling exploitdb-papers
sudo apt install -y -t kali-rolling ext3grep
sudo apt install -y -t kali-rolling ext4magic
sudo apt install -y -t kali-rolling extundelete
sudo apt install -y -t kali-rolling eyewitness
sudo apt install -y -t kali-rolling faraday-agent-dispatcher
sudo apt install -y -t kali-rolling faraday-cli
sudo apt install -y -t kali-rolling fatcat
sudo apt install -y -t kali-rolling fcrackzip
sudo apt install -y -t kali-rolling fern-wifi-cracker
sudo apt install -y -t kali-rolling feroxbuster
sudo apt install -y -t kali-rolling ferret-sidejack
sudo apt install -y -t kali-rolling ffuf
sudo apt install -y -t kali-rolling fierce
sudo apt install -y -t kali-rolling fiked
sudo apt install -y -t kali-rolling finalrecon
sudo apt install -y -t kali-rolling firefox-developer-edition-kbx
sudo apt install -y -t kali-rolling firewalk
sudo apt install -y -t kali-rolling firmware-mod-kit
sudo apt install -y -t kali-rolling flashrom
sudo apt install -y -t kali-rolling foremost
sudo apt install -y -t kali-rolling forensic-artifacts
sudo apt install -y -t kali-rolling forensics-colorize
sudo apt install -y -t kali-rolling fping
sudo apt install -y -t kali-rolling fragrouter
sudo apt install -y -t kali-rolling framework2
sudo apt install -y -t kali-rolling freeradius
sudo apt install -y -t kali-rolling freeradius-wpe
sudo apt install -y -t kali-rolling freerdp2
sudo apt install -y -t kali-rolling ftester
sudo apt install -y -t kali-rolling fuse3
sudo apt install -y -t kali-rolling fwbuilder
sudo apt install -y -t kali-rolling galleta
sudo apt install -y -t kali-rolling gdb-peda
sudo apt install -y -t kali-rolling gdisk
sudo apt install -y -t kali-rolling getallurls
sudo apt install -y -t kali-rolling ghidra
sudo apt install -y -t kali-rolling git
sudo apt install -y -t kali-rolling gitleaks
sudo apt install -y -t kali-rolling glibc
sudo apt install -y -t kali-rolling gnuradio
sudo apt install -y -t kali-rolling gobuster
sudo apt install -y -t kali-rolling godoh
sudo apt install -y -t kali-rolling golang-github-binject-go-donut
sudo apt install -y -t kali-rolling goldeneye
sudo apt install -y -t kali-rolling goofile
sudo apt install -y -t kali-rolling google-nexus-tools
sudo apt install -y -t kali-rolling gophish
sudo apt install -y -t kali-rolling gospider
sudo apt install -y -t kali-rolling gpart
sudo apt install -y -t kali-rolling gparted
sudo apt install -y -t kali-rolling gpp-decrypt
sudo apt install -y -t kali-rolling gqrx-sdr
sudo apt install -y -t kali-rolling gr-air-modes
sudo apt install -y -t kali-rolling gr-iqbal
sudo apt install -y -t kali-rolling gr-osmosdr
sudo apt install -y -t kali-rolling grokevt
sudo apt install -y -t kali-rolling gss-ntlmssp
sudo apt install -y -t kali-rolling gtkhash
sudo apt install -y -t kali-rolling guymager
sudo apt install -y -t kali-rolling gvm
sudo apt install -y -t kali-rolling h8mail
sudo apt install -y -t kali-rolling hackrf
sudo apt install -y -t kali-rolling hak5-wifi-coconut
sudo apt install -y -t kali-rolling hakrawler
sudo apt install -y -t kali-rolling hamster-sidejack
sudo apt install -y -t kali-rolling hash-identifier
sudo apt install -y -t kali-rolling hashcat
sudo apt install -y -t kali-rolling hashcat-utils
sudo apt install -y -t kali-rolling hashdeep
sudo apt install -y -t kali-rolling hashid
sudo apt install -y -t kali-rolling hashrat
sudo apt install -y -t kali-rolling havoc
sudo apt install -y -t kali-rolling hb-honeypot
sudo apt install -y -t kali-rolling hcxtools
sudo apt install -y -t kali-rolling heartleech
sudo apt install -y -t kali-rolling hexinject
sudo apt install -y -t kali-rolling hivex
sudo apt install -y -t kali-rolling hostapd-mana
sudo apt install -y -t kali-rolling hostapd-wpe
sudo apt install -y -t kali-rolling hosthunter
sudo apt install -y -t kali-rolling hostsman
sudo apt install -y -t kali-rolling hotpatch
sudo apt install -y -t kali-rolling hping3
sudo apt install -y -t kali-rolling htshells
sudo apt install -y -t kali-rolling httprint
sudo apt install -y -t kali-rolling httprobe
sudo apt install -y -t kali-rolling httpx-toolkit
sudo apt install -y -t kali-rolling httrack
sudo apt install -y -t kali-rolling hubble
sudo apt install -y -t kali-rolling humble
sudo apt install -y -t kali-rolling hurl
sudo apt install -y -t kali-rolling hydra
sudo apt install -y -t kali-rolling hyperion
sudo apt install -y -t kali-rolling i2c-tools
sudo apt install -y -t kali-rolling iaxflood
sudo apt install -y -t kali-rolling ibombshell
sudo apt install -y -t kali-rolling ident-user-enum
sudo apt install -y -t kali-rolling ifenslave
sudo apt install -y -t kali-rolling ike-scan
sudo apt install -y -t kali-rolling imhex
sudo apt install -y -t kali-rolling impacket
sudo apt install -y -t kali-rolling impacket-scripts
sudo apt install -y -t kali-rolling inetsim
sudo apt install -y -t kali-rolling inspectrum
sudo apt install -y -t kali-rolling inspy
sudo apt install -y -t kali-rolling instaloader
sudo apt install -y -t kali-rolling intrace
sudo apt install -y -t kali-rolling inviteflood
sudo apt install -y -t kali-rolling iodine
sudo apt install -y -t kali-rolling ipv6toolkit
sudo apt install -y -t kali-rolling irpas
sudo apt install -y -t kali-rolling ismtp
sudo apt install -y -t kali-rolling isr-evilgrade
sudo apt install -y -t kali-rolling ivre
sudo apt install -y -t kali-rolling iw
sudo apt install -y -t kali-rolling jadx
sudo apt install -y -t kali-rolling javasnoop
sudo apt install -y -t kali-rolling jboss-autopwn
sudo apt install -y -t kali-rolling jd-gui
sudo apt install -y -t kali-rolling john
sudo apt install -y -t kali-rolling johnny
sudo apt install -y -t kali-rolling joomscan
sudo apt install -y -t kali-rolling joplin
sudo apt install -y -t kali-rolling jsp-file-browser
sudo apt install -y -t kali-rolling jsql
sudo apt install -y -t kali-rolling juice-shop
sudo apt install -y -t kali-rolling kali-autopilot
sudo apt install -y -t kali-rolling kali-community-wallpapers
sudo apt install -y -t kali-rolling kali-defaults
sudo apt install -y -t kali-rolling kali-meta
sudo apt install -y -t kali-rolling kali-tweaks
sudo apt install -y -t kali-rolling kali-wallpapers
sudo apt install -y -t kali-rolling kalibrate-rtl
sudo apt install -y -t kali-rolling kerberoast
sudo apt install -y -t kali-rolling kismet
sudo apt install -y -t kali-rolling knocker
sudo apt install -y -t kali-rolling koadic
sudo apt install -y -t kali-rolling kubernetes-helm
sudo apt install -y -t kali-rolling kustomize
sudo apt install -y -t kali-rolling lapsdumper
sudo apt install -y -t kali-rolling laudanum
sudo apt install -y -t kali-rolling lbd
sudo apt install -y -t kali-rolling legion
sudo apt install -y -t kali-rolling libewf
sudo apt install -y -t kali-rolling libfindrtp
sudo apt install -y -t kali-rolling libfreefare
sudo apt install -y -t kali-rolling libimage-exiftool-perl
sudo apt install -y -t kali-rolling libnfc
sudo apt install -y -t kali-rolling libpst
sudo apt install -y -t kali-rolling libsmali-java
sudo apt install -y -t kali-rolling linux-exploit-suggester
sudo apt install -y -t kali-rolling llvm-defaults
sudo apt install -y -t kali-rolling lvm2
sudo apt install -y -t kali-rolling lynis
sudo apt install -y -t kali-rolling mac-robber
sudo apt install -y -t kali-rolling macchanger
sudo apt install -y -t kali-rolling magicrescue
sudo apt install -y -t kali-rolling maltego
sudo apt install -y -t kali-rolling maltego-teeth
sudo apt install -y -t kali-rolling maryam
sudo apt install -y -t kali-rolling maskprocessor
sudo apt install -y -t kali-rolling masscan
sudo apt install -y -t kali-rolling massdns
sudo apt install -y -t kali-rolling mc
sudo apt install -y -t kali-rolling mdbtools
sudo apt install -y -t kali-rolling mdk3
sudo apt install -y -t kali-rolling mdk4
sudo apt install -y -t kali-rolling medusa
sudo apt install -y -t kali-rolling memdump
sudo apt install -y -t kali-rolling mercurial
sudo apt install -y -t kali-rolling merlin
sudo apt install -y -t kali-rolling merlin-agent
sudo apt install -y -t kali-rolling metacam
sudo apt install -y -t kali-rolling metagoofil
sudo apt install -y -t kali-rolling metasploit-framework
sudo apt install -y -t kali-rolling mfcuk
sudo apt install -y -t kali-rolling mfoc
sudo apt install -y -t kali-rolling mfterm
sudo apt install -y -t kali-rolling mimikatz
sudo apt install -y -t kali-rolling minicom
sudo apt install -y -t kali-rolling miredo
sudo apt install -y -t kali-rolling missidentify
sudo apt install -y -t kali-rolling mitmproxy
sudo apt install -y -t kali-rolling mongo-tools
sudo apt install -y -t kali-rolling msfpc
sudo apt install -y -t kali-rolling multiforcer
sudo apt install -y -t kali-rolling multimac
sudo apt install -y -t kali-rolling multimon-ng
sudo apt install -y -t kali-rolling myrescue
sudo apt install -y -t kali-rolling mysql-defaults
sudo apt install -y -t kali-rolling naabu
sudo apt install -y -t kali-rolling name-that-hash
sudo apt install -y -t kali-rolling nasm
sudo apt install -y -t kali-rolling nasty
sudo apt install -y -t kali-rolling nbtscan
sudo apt install -y -t kali-rolling nbtscan-unixwiz
sudo apt install -y -t kali-rolling ncat-w32
sudo apt install -y -t kali-rolling ncrack
sudo apt install -y -t kali-rolling ncurses-hexedit
sudo apt install -y -t kali-rolling net-snmp
sudo apt install -y -t kali-rolling net-tools
sudo apt install -y -t kali-rolling netbase
sudo apt install -y -t kali-rolling netcat
sudo apt install -y -t kali-rolling netdiscover
sudo apt install -y -t kali-rolling netmask
sudo apt install -y -t kali-rolling netsed
sudo apt install -y -t kali-rolling netsniff-ng
sudo apt install -y -t kali-rolling netw-ib-ox-ag
sudo apt install -y -t kali-rolling nextnet
sudo apt install -y -t kali-rolling nfs-utils
sudo apt install -y -t kali-rolling ngrep
sudo apt install -y -t kali-rolling nikto
sudo apt install -y -t kali-rolling nipper-ng
sudo apt install -y -t kali-rolling nishang
sudo apt install -y -t kali-rolling nmap
sudo apt install -y -t kali-rolling nmapsi4
sudo apt install -y -t kali-rolling nuclei
sudo apt install -y -t kali-rolling o-saft
sudo apt install -y -t kali-rolling oclgausscrack
sudo apt install -y -t kali-rolling odat
sudo apt install -y -t kali-rolling offsec-courses
sudo apt install -y -t kali-rolling ohrwurm
sudo apt install -y -t kali-rolling ollydbg
sudo apt install -y -t kali-rolling onesixtyone
sudo apt install -y -t kali-rolling openocd
sudo apt install -y -t kali-rolling openssh
sudo apt install -y -t kali-rolling openvpn
sudo apt install -y -t kali-rolling ophcrack
sudo apt install -y -t kali-rolling oscanner
sudo apt install -y -t kali-rolling osrframework
sudo apt install -y -t kali-rolling outguess
sudo apt install -y -t kali-rolling owasp-mantra-ff
sudo apt install -y -t kali-rolling owl
sudo apt install -y -t kali-rolling p0f
sudo apt install -y -t kali-rolling p7zip
sudo apt install -y -t kali-rolling pack
sudo apt install -y -t kali-rolling pack2
sudo apt install -y -t kali-rolling pacu
sudo apt install -y -t kali-rolling padbuster
sudo apt install -y -t kali-rolling paros
sudo apt install -y -t kali-rolling parsero
sudo apt install -y -t kali-rolling parted
sudo apt install -y -t kali-rolling pasco
sudo apt install -y -t kali-rolling passdetective
sudo apt install -y -t kali-rolling passing-the-hash
sudo apt install -y -t kali-rolling patator
sudo apt install -y -t kali-rolling payloadsallthethings
sudo apt install -y -t kali-rolling pdf-parser
sudo apt install -y -t kali-rolling pdfcrack
sudo apt install -y -t kali-rolling pdfid
sudo apt install -y -t kali-rolling peass-ng
sudo apt install -y -t kali-rolling peirates
sudo apt install -y -t kali-rolling perl-cisco-copyconfig
sudo apt install -y -t kali-rolling pev
sudo apt install -y -t kali-rolling phishery
sudo apt install -y -t kali-rolling photon
sudo apt install -y -t kali-rolling php-defaults
sudo apt install -y -t kali-rolling phpggc
sudo apt install -y -t kali-rolling phpsploit
sudo apt install -y -t kali-rolling pipal
sudo apt install -y -t kali-rolling pixiewps
sudo apt install -y -t kali-rolling plaso
sudo apt install -y -t kali-rolling plocate
sudo apt install -y -t kali-rolling pnscan
sudo apt install -y -t kali-rolling pocsuite3
sudo apt install -y -t kali-rolling polenum
sudo apt install -y -t kali-rolling pompem
sudo apt install -y -t kali-rolling portspoof
sudo apt install -y -t kali-rolling poshc2
sudo apt install -y -t kali-rolling powercat
sudo apt install -y -t kali-rolling powershell
sudo apt install -y -t kali-rolling powershell-empire
sudo apt install -y -t kali-rolling powersploit
sudo apt install -y -t kali-rolling princeprocessor
sudo apt install -y -t kali-rolling protos-sip
sudo apt install -y -t kali-rolling proxify
sudo apt install -y -t kali-rolling proxmark3
sudo apt install -y -t kali-rolling proxychains-ng
sudo apt install -y -t kali-rolling proxytunnel
sudo apt install -y -t kali-rolling pskracker
sudo apt install -y -t kali-rolling ptunnel
sudo apt install -y -t kali-rolling pwnat
sudo apt install -y -t kali-rolling pwncat
sudo apt install -y -t kali-rolling python-defaults
sudo apt install -y -t kali-rolling python-faraday
sudo apt install -y -t kali-rolling python-ldapdomaindump
sudo apt install -y -t kali-rolling python-pip
sudo apt install -y -t kali-rolling python-virtualenv
sudo apt install -y -t kali-rolling qemu
sudo apt install -y -t kali-rolling qsslcaudit
sudo apt install -y -t kali-rolling quark-engine
sudo apt install -y -t kali-rolling radare2
sudo apt install -y -t kali-rolling rainbowcrack
sudo apt install -y -t kali-rolling rake
sudo apt install -y -t kali-rolling rarcrack
sudo apt install -y -t kali-rolling raven
sudo apt install -y -t kali-rolling rcracki-mt
sudo apt install -y -t kali-rolling rdesktop
sudo apt install -y -t kali-rolling reaver
sudo apt install -y -t kali-rolling rebind
sudo apt install -y -t kali-rolling recon-ng
sudo apt install -y -t kali-rolling reconspider
sudo apt install -y -t kali-rolling recordmydesktop
sudo apt install -y -t kali-rolling recoverdm
sudo apt install -y -t kali-rolling recoverjpeg
sudo apt install -y -t kali-rolling redeye
sudo apt install -y -t kali-rolling redfang
sudo apt install -y -t kali-rolling redsnarf
sudo apt install -y -t kali-rolling redsocks
sudo apt install -y -t kali-rolling reglookup
sudo apt install -y -t kali-rolling regripper
sudo apt install -y -t kali-rolling rekono-kbx
sudo apt install -y -t kali-rolling rephrase
sudo apt install -y -t kali-rolling requests
sudo apt install -y -t kali-rolling responder
sudo apt install -y -t kali-rolling rev-proxy-grapher
sudo apt install -y -t kali-rolling rfcat
sudo apt install -y -t kali-rolling rfdump
sudo apt install -y -t kali-rolling ridenum
sudo apt install -y -t kali-rolling rifiuti
sudo apt install -y -t kali-rolling rifiuti2
sudo apt install -y -t kali-rolling rizin-cutter
sudo apt install -y -t kali-rolling rkhunter
sudo apt install -y -t kali-rolling rling
sudo apt install -y -t kali-rolling robotstxt
sudo apt install -y -t kali-rolling ropper
sudo apt install -y -t kali-rolling routerkeygenpc
sudo apt install -y -t kali-rolling routersploit
sudo apt install -y -t kali-rolling rsakeyfind
sudo apt install -y -t kali-rolling rsmangler
sudo apt install -y -t kali-rolling rtlsdr-scanner
sudo apt install -y -t kali-rolling rtpbreak
sudo apt install -y -t kali-rolling rtpflood
sudo apt install -y -t kali-rolling rtpinsertsound
sudo apt install -y -t kali-rolling rtpmixsound
sudo apt install -y -t kali-rolling ruby-pedump
sudo apt install -y -t kali-rolling rz-ghidra
sudo apt install -y -t kali-rolling s3scanner
sudo apt install -y -t kali-rolling safecopy
sudo apt install -y -t kali-rolling sakis3g
sudo apt install -y -t kali-rolling samba
sudo apt install -y -t kali-rolling samdump2
sudo apt install -y -t kali-rolling sbd
sudo apt install -y -t kali-rolling scalpel
sudo apt install -y -t kali-rolling scapy
sudo apt install -y -t kali-rolling screen
sudo apt install -y -t kali-rolling scrounge-ntfs
sudo apt install -y -t kali-rolling sctpscan
sudo apt install -y -t kali-rolling seclists
sudo apt install -y -t kali-rolling secure-socket-funneling
sudo apt install -y -t kali-rolling sendemail
sudo apt install -y -t kali-rolling sentrypeer
sudo apt install -y -t kali-rolling set
sudo apt install -y -t kali-rolling sfuzz
sudo apt install -y -t kali-rolling shed
sudo apt install -y -t kali-rolling shellfire
sudo apt install -y -t kali-rolling shellnoob
sudo apt install -y -t kali-rolling shellter
sudo apt install -y -t kali-rolling sherlock
sudo apt install -y -t kali-rolling sidguesser
sudo apt install -y -t kali-rolling siege
sudo apt install -y -t kali-rolling sigma-cli
sudo apt install -y -t kali-rolling silenttrinity
sudo apt install -y -t kali-rolling siparmyknife
sudo apt install -y -t kali-rolling sipcrack
sudo apt install -y -t kali-rolling sipp
sudo apt install -y -t kali-rolling sipsak
sudo apt install -y -t kali-rolling sipvicious
sudo apt install -y -t kali-rolling skipfish
sudo apt install -y -t kali-rolling sleuthkit
sudo apt install -y -t kali-rolling slimtoolkit
sudo apt install -y -t kali-rolling sliver
sudo apt install -y -t kali-rolling slowhttptest
sudo apt install -y -t kali-rolling smbmap
sudo apt install -y -t kali-rolling smtp-user-enum
sudo apt install -y -t kali-rolling sn0int
sudo apt install -y -t kali-rolling sniffjoke
sudo apt install -y -t kali-rolling snmpcheck
sudo apt install -y -t kali-rolling snmpenum
sudo apt install -y -t kali-rolling snowdrop
sudo apt install -y -t kali-rolling socat
sudo apt install -y -t kali-rolling sparrow-wifi
sudo apt install -y -t kali-rolling spectools
sudo apt install -y -t kali-rolling spiderfoot
sudo apt install -y -t kali-rolling spike
sudo apt install -y -t kali-rolling spire
sudo apt install -y -t kali-rolling spooftooph
sudo apt install -y -t kali-rolling spray
sudo apt install -y -t kali-rolling sprayingtoolkit
sudo apt install -y -t kali-rolling spraykatz
sudo apt install -y -t kali-rolling sqldict
sudo apt install -y -t kali-rolling sqlitebrowser
sudo apt install -y -t kali-rolling sqlmap
sudo apt install -y -t kali-rolling sqlninja
sudo apt install -y -t kali-rolling sqlsus
sudo apt install -y -t kali-rolling ssdeep
sudo apt install -y -t kali-rolling ssldump
sudo apt install -y -t kali-rolling sslh
sudo apt install -y -t kali-rolling sslscan
sudo apt install -y -t kali-rolling sslsniff
sudo apt install -y -t kali-rolling sslsplit
sudo apt install -y -t kali-rolling sslstrip
sudo apt install -y -t kali-rolling sslyze
sudo apt install -y -t kali-rolling statsprocessor
sudo apt install -y -t kali-rolling stegcracker
sudo apt install -y -t kali-rolling steghide
sudo apt install -y -t kali-rolling stegsnow
sudo apt install -y -t kali-rolling stunnel4
sudo apt install -y -t kali-rolling subfinder
sudo apt install -y -t kali-rolling subjack
sudo apt install -y -t kali-rolling sublist3r
sudo apt install -y -t kali-rolling subversion
sudo apt install -y -t kali-rolling sucrack
sudo apt install -y -t kali-rolling sudo
sudo apt install -y -t kali-rolling swaks
sudo apt install -y -t kali-rolling syft
sudo apt install -y -t kali-rolling t50
sudo apt install -y -t kali-rolling tcpdump
sudo apt install -y -t kali-rolling tcpflow
sudo apt install -y -t kali-rolling tcpick
sudo apt install -y -t kali-rolling tcpreplay
sudo apt install -y -t kali-rolling teamsploit
sudo apt install -y -t kali-rolling termineter
sudo apt install -y -t kali-rolling terraform
sudo apt install -y -t kali-rolling testdisk
sudo apt install -y -t kali-rolling testssl.sh
sudo apt install -y -t kali-rolling tetragon
sudo apt install -y -t kali-rolling tftp-hpa
sudo apt install -y -t kali-rolling tftpd32
sudo apt install -y -t kali-rolling thc-ipv6
sudo apt install -y -t kali-rolling thc-pptp-bruter
sudo apt install -y -t kali-rolling thc-ssl-dos
sudo apt install -y -t kali-rolling theharvester
sudo apt install -y -t kali-rolling tiger
sudo apt install -y -t kali-rolling tightvnc
sudo apt install -y -t kali-rolling tlssled
sudo apt install -y -t kali-rolling tmux
sudo apt install -y -t kali-rolling tnftp
sudo apt install -y -t kali-rolling tnscmd10g
sudo apt install -y -t kali-rolling traceroute
sudo apt install -y -t kali-rolling trivy
sudo apt install -y -t kali-rolling truecrack
sudo apt install -y -t kali-rolling trufflehog
sudo apt install -y -t kali-rolling tundeep
sudo apt install -y -t kali-rolling twofi
sudo apt install -y -t kali-rolling tzdata
sudo apt install -y -t kali-rolling ubertooth
sudo apt install -y -t kali-rolling udptunnel
sudo apt install -y -t kali-rolling uhd
sudo apt install -y -t kali-rolling uhd-images
sudo apt install -y -t kali-rolling unar
sudo apt install -y -t kali-rolling unblob
sudo apt install -y -t kali-rolling undbx
sudo apt install -y -t kali-rolling unhide
sudo apt install -y -t kali-rolling unhide.rb
sudo apt install -y -t kali-rolling unicorn-magic
sudo apt install -y -t kali-rolling unicornscan
sudo apt install -y -t kali-rolling uniscan
sudo apt install -y -t kali-rolling unix-privesc-check
sudo apt install -y -t kali-rolling unrar-nonfree
sudo apt install -y -t kali-rolling upx-ucl
sudo apt install -y -t kali-rolling urlcrazy
sudo apt install -y -t kali-rolling util-linux
sudo apt install -y -t kali-rolling vboot-utils
sudo apt install -y -t kali-rolling veil
sudo apt install -y -t kali-rolling villain
sudo apt install -y -t kali-rolling vim
sudo apt install -y -t kali-rolling vinetto
sudo apt install -y -t kali-rolling vlan
sudo apt install -y -t kali-rolling voiphopper
sudo apt install -y -t kali-rolling vpnc
sudo apt install -y -t kali-rolling wafw00f
sudo apt install -y -t kali-rolling wapiti
sudo apt install -y -t kali-rolling watobo
sudo apt install -y -t kali-rolling wce
sudo apt install -y -t kali-rolling webacoo
sudo apt install -y -t kali-rolling webscarab
sudo apt install -y -t kali-rolling webshells
sudo apt install -y -t kali-rolling websploit
sudo apt install -y -t kali-rolling weevely
sudo apt install -y -t kali-rolling wfuzz
sudo apt install -y -t kali-rolling wget
sudo apt install -y -t kali-rolling wgetpaste
sudo apt install -y -t kali-rolling what-is-python
sudo apt install -y -t kali-rolling whatmask
sudo apt install -y -t kali-rolling whatweb
sudo apt install -y -t kali-rolling whois
sudo apt install -y -t kali-rolling wifi-honey
sudo apt install -y -t kali-rolling wifiphisher
sudo apt install -y -t kali-rolling wifipumpkin3
sudo apt install -y -t kali-rolling wifite
sudo apt install -y -t kali-rolling wig
sudo apt install -y -t kali-rolling wig-ng
sudo apt install -y -t kali-rolling windows-binaries
sudo apt install -y -t kali-rolling windows-privesc-check
sudo apt install -y -t kali-rolling winexe
sudo apt install -y -t kali-rolling winregfs
sudo apt install -y -t kali-rolling wireshark
sudo apt install -y -t kali-rolling witnessme
sudo apt install -y -t kali-rolling wmi
sudo apt install -y -t kali-rolling wordlistraider
sudo apt install -y -t kali-rolling wordlists
sudo apt install -y -t kali-rolling wotmate
sudo apt install -y -t kali-rolling wpa-sycophant
sudo apt install -y -t kali-rolling wpscan
sudo apt install -y -t kali-rolling wsgidav
sudo apt install -y -t kali-rolling xmount
sudo apt install -y -t kali-rolling xplico
sudo apt install -y -t kali-rolling xspy
sudo apt install -y -t kali-rolling xsser
sudo apt install -y -t kali-rolling yara
sudo apt install -y -t kali-rolling yersinia
sudo apt install -y -t kali-rolling zaproxy
sudo apt install -y -t kali-rolling zenmap-kbx
sudo apt install -y -t kali-rolling zerofree
sudo apt install -y -t kali-rolling zim
sudo apt install -y -t kali-rolling zonedb
sudo apt install -y -t kali-rolling zsh
sudo apt install -y -t kali-rolling zsh-autosuggestions
sudo apt install -y -t kali-rolling zsh-syntax-highlighting
sudo apt install -y -t kali-rolling 