
start "Loggly analytics"   /LOW powershell -C "$ErrorActionPreference = 'Stop'; e:; cd e:\dsv\pf-main\tools\scripts; .\LogglyUtils.ps1; Loggly-ExceptionsToSQLite -SQLiteConnectionStringOrFileName E:\dsv\pfMetrics.db -from '2019-03-30T03:33:08Z' -Cloud 'analytics'   -Vertical 'analytics';    "
start "Loggly devservices" /LOW powershell -C "$ErrorActionPreference = 'Stop'; e:; cd e:\dsv\pf-main\tools\scripts; .\LogglyUtils.ps1; Loggly-ExceptionsToSQLite -SQLiteConnectionStringOrFileName E:\dsv\pfMetrics.db -from '2019-03-30T03:33:08Z' -Cloud 'devservices' -Vertical 'devservices' ; "
start "Loggly main"        /LOW powershell -C "$ErrorActionPreference = 'Stop'; e:; cd e:\dsv\pf-main\tools\scripts; .\LogglyUtils.ps1; Loggly-ExceptionsToSQLite -SQLiteConnectionStringOrFileName E:\dsv\pfMetrics.db -from '2019-03-30T03:33:08Z' -Cloud 'main'        -Vertical 'low' ;         "
start "Loggly main"        /LOW powershell -C "$ErrorActionPreference = 'Stop'; e:; cd e:\dsv\pf-main\tools\scripts; .\LogglyUtils.ps1; Loggly-ExceptionsToSQLite -SQLiteConnectionStringOrFileName E:\dsv\pfMetrics.db -from '2019-03-30T03:33:08Z' -Cloud 'main'        -Vertical 'master';       " 
start "Loggly player-svcs" /LOW powershell -C "$ErrorActionPreference = 'Stop'; e:; cd e:\dsv\pf-main\tools\scripts; .\LogglyUtils.ps1; Loggly-ExceptionsToSQLite -SQLiteConnectionStringOrFileName E:\dsv\pfMetrics.db -from '2019-03-30T03:33:08Z' -Cloud 'player-svcs' -Vertical 'player-svcs';  "
start "Loggly rblx"        /LOW powershell -C "$ErrorActionPreference = 'Stop'; e:; cd e:\dsv\pf-main\tools\scripts; .\LogglyUtils.ps1; Loggly-ExceptionsToSQLite -SQLiteConnectionStringOrFileName E:\dsv\pfMetrics.db -from '2019-03-30T03:33:08Z' -Cloud 'rblx'        -Vertical 'rblx';         "
start "Loggly spi"         /LOW powershell -C "$ErrorActionPreference = 'Stop'; e:; cd e:\dsv\pf-main\tools\scripts; .\LogglyUtils.ps1; Loggly-ExceptionsToSQLite -SQLiteConnectionStringOrFileName E:\dsv\pfMetrics.db -from '2019-03-30T03:33:08Z' -Cloud 'spi'         -Vertical 'spi';          "
start "Loggly upr-ush"     /LOW powershell -C "$ErrorActionPreference = 'Stop'; e:; cd e:\dsv\pf-main\tools\scripts; .\LogglyUtils.ps1; Loggly-ExceptionsToSQLite -SQLiteConnectionStringOrFileName E:\dsv\pfMetrics.db -from '2019-03-30T03:33:08Z' -Cloud 'upr-ush'     -Vertical 'upr-ush';      "
start "Loggly upr-usj"     /LOW powershell -C "$ErrorActionPreference = 'Stop'; e:; cd e:\dsv\pf-main\tools\scripts; .\LogglyUtils.ps1; Loggly-ExceptionsToSQLite -SQLiteConnectionStringOrFileName E:\dsv\pfMetrics.db -from '2019-03-30T03:33:08Z' -Cloud 'upr-usj'     -Vertical 'upr-usj' ;     "
start "DataDog"            /LOW powershell -C "$ErrorActionPreference = 'Stop'; e:; cd e:\dsv\pf-main\tools\scripts; .\DataDogUtils.ps1;DataDog-GetAllAvailableSuccessAndErrorMetricsToSQLite -SQLiteConnectionStringOrFileName E:\dsv\pfMetrics.db ;                                               "

